/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import javax.swing.JOptionPane;
import model.User;
import dataaccessobject.UserDataAccessObject;
/**
 *
 * @author chloeglynn
 */
public class Signup extends javax.swing.JFrame {
    
    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    public String mobileNumberPattern = "[0-9]*$";

    /**
     * Creates new form Signup
     */
    
    //methods
    
    public Signup() {
        initComponents();
        btnSave.setEnabled(false);
    }
    
    public void clear(){
        signupName.setText("");
        signupEmail.setText("");
        signupMobile.setText("");
        signupQuestion.setText("");
        signupAnswer.setText("");
        signupPassword.setText("");
        btnSave.setEnabled(false);
    }
    
    public void validateFields(){
        String name = signupName.getText();
        String email = signupEmail.getText();
        String mobileNumber = signupMobile.getText();
        String password = signupPassword.getText();
        String securityQuestion = signupQuestion.getText();
        String answer = signupAnswer.getText();
        if(!name.equals("") && email.matches(emailPattern) && mobileNumber.matches(mobileNumberPattern) && mobileNumber.length() == 10 && !password.equals("") && !securityQuestion.equals("") && !answer.equals(""))
            btnSave.setEnabled(true);
        else
            btnSave.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        signupName = new javax.swing.JTextField();
        signupEmail = new javax.swing.JTextField();
        signupMobile = new javax.swing.JTextField();
        signupPassword = new javax.swing.JPasswordField();
        signupQuestion = new javax.swing.JTextField();
        signupAnswer = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.red);
        setMinimumSize(new java.awt.Dimension(1366, 786));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Avenir Next", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Signup");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 337, -1, -1));

        jLabel3.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 381, -1, -1));

        jLabel4.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jLabel4.setText("Mobile No.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 425, -1, -1));

        jLabel5.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jLabel5.setText("Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 469, -1, -1));

        jLabel6.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jLabel6.setText("Security Question");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 513, -1, -1));

        jLabel7.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jLabel7.setText("Answer");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 557, -1, -1));

        signupName.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        signupName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupNameActionPerformed(evt);
            }
        });
        signupName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                signupNameKeyReleased(evt);
            }
        });
        getContentPane().add(signupName, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 334, 351, -1));

        signupEmail.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        signupEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                signupEmailKeyReleased(evt);
            }
        });
        getContentPane().add(signupEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 378, 351, -1));

        signupMobile.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        signupMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupMobileActionPerformed(evt);
            }
        });
        signupMobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                signupMobileKeyReleased(evt);
            }
        });
        getContentPane().add(signupMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 422, 351, -1));

        signupPassword.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        signupPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                signupPasswordKeyReleased(evt);
            }
        });
        getContentPane().add(signupPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 466, 351, -1));

        signupQuestion.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        signupQuestion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                signupQuestionKeyReleased(evt);
            }
        });
        getContentPane().add(signupQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 510, 351, -1));

        signupAnswer.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        signupAnswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                signupAnswerKeyReleased(evt);
            }
        });
        getContentPane().add(signupAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 554, 351, -1));

        btnSave.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 611, -1, -1));

        btnClear.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 611, -1, -1));

        btnExit.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit small.png"))); // NOI18N
        btnExit.setText("Exit");
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 610, -1, -1));

        jButton4.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        jButton4.setText("Login");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 652, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Forgot Password?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 650, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupNameActionPerformed
      
    }//GEN-LAST:event_signupNameActionPerformed

    private void signupMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupMobileActionPerformed
        
    }//GEN-LAST:event_signupMobileActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // display login page
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // save new user info to database
        User user = new User();
        user.setName(signupName.getText());
        user.setEmail(signupEmail.getText());
        user.setMobileNumber(signupMobile.getText());
        user.setPassword(signupPassword.getText());
        user.setQuestion(signupQuestion.getText());
        user.setAnswer(signupAnswer.getText());
        UserDataAccessObject.save(user);
        clear();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        //clear fields
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void signupNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signupNameKeyReleased
        // validate fields
        validateFields();
    }//GEN-LAST:event_signupNameKeyReleased

    private void signupEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signupEmailKeyReleased
        // validate fields
        validateFields();
    }//GEN-LAST:event_signupEmailKeyReleased

    private void signupMobileKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signupMobileKeyReleased
        // validate fields
        validateFields();
    }//GEN-LAST:event_signupMobileKeyReleased

    private void signupPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signupPasswordKeyReleased
        // validate fields
        validateFields();
    }//GEN-LAST:event_signupPasswordKeyReleased

    private void signupQuestionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signupQuestionKeyReleased
        //validate fields
        validateFields();
    }//GEN-LAST:event_signupQuestionKeyReleased

    private void signupAnswerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signupAnswerKeyReleased
        // validate fields
        validateFields();
    }//GEN-LAST:event_signupAnswerKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // display Forgot Password page
        setVisible(false);
        new ForgotPassword().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {
        //exit application
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to exit?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField signupAnswer;
    private javax.swing.JTextField signupEmail;
    private javax.swing.JTextField signupMobile;
    private javax.swing.JTextField signupName;
    private javax.swing.JPasswordField signupPassword;
    private javax.swing.JTextField signupQuestion;
    // End of variables declaration//GEN-END:variables
}
